apisix:
  node_listen:
    - port: 9080
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9090

plugins:
  - openid-connect
  - grpc-transcode
  - serverless-pre-function
  - opentelemetry

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_key:
      - name: admin
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin
    allow_admin:
      - 0.0.0.0/0
    admin_listen:
      ip: 0.0.0.0
      port: 9180
  etcd:
    host:
      - "http://etcd:2379"
    prefix: /apisix

discovery:
  consul:
    servers:
      - "http://consul:8500"
